export interface Sectors {
    automotive?: string,
    b2b?: string,
    tech?: string,
    eroticism?: string,
    leisureGames?: string,
    datingSocial?: string,
    health?: string,
    household?: string,
    realEstate?: string,
    media?: string,
    career?: string,
    youth?: string,
    cultureEntertainment?: string,
    pressMagazines?: string,
    travel?:string,
    shopping?:string,
    sportNutrition?:string,
    animals?:string,
    economyFinance?:string,
    science?:string,
}