export enum Sector {
    automotive = 'Auto, Verkehr \& Motorsport',
    b2b = 'B2B',
    tech = 'Computer \& Technik',
    eroticism = 'Erotik',
    leisureGames = 'Freizeit \& Spiele',
    datingSocial = 'Gesellschaft \& Dating',
    health = 'Gesundheit \& Pflege',
    household = 'Haus \& Garten',
    realEstate = 'Immobilien',
    media = 'Internet \& Medien',
    career = 'Karriere \& Bildung',
    youth = 'Kinder \& Jugend',
    cultureEntertainment = 'Kultur \& Unterhaltung',
    pressMagazines = 'Nachrichten \& Magazine',
    travel = 'Reisen \& Natur',
    shopping = 'Shopping \& E-Commerce',
    sportNutrition = 'Sport \& Ernährung',
    animals = 'Tiere \& Haustiere',
    economyFinance = 'Wirtschaft \& Finanzen',
    science = 'Wissen \& Wissenschaft',
}